### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Nifty0x** [ddupont808/GPT-4V-Act#3]
@ddupont808 I tried to replicate what you showed in your demo but keep getting errors/rejections. 

The response I get in the UI "I don't have the capability to interact with a search bar or perform live actions such as typing or browsing the internet...."

Error: 
(node:30692) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\Admin\ai-browser\tmp\screenshot.png'

Can you help with that?

**Comment by tseven** [comment]
You may need to manually create the `tmp` folder.
That's what worked for me.

**Comment by Nifty0x** [comment]
Yea, I was thinking of it but not sure why I havn't tested. It works now, thanks @tseven!
