### ISSUE TITLE
如何使用GPT-4v-act

### ISSUE THREAD

**Issue by rangmiao** [ddupont808/GPT-4V-Act#6]
作者你好，在使用时遇到了无法正常调用gpt4v的情况，右侧框输入对应命令，没有相应的响应，命令行界面报如下错误：
<img width="1433" alt="image" src="https://github.com/ddupont808/GPT-4V-Act/assets/33169348/d295da05-e323-4a55-8696-6b355bca64c8">

想问下这个可以怎么解决呢？
还有个疑问，在使用过程中未能找到chatgpt4 的账户密码设置地方，是和这个有关吗？

**Comment by galaxy24** [comment]
> 作者你好，在使用时遇到了无法正常调用gpt4v的情况，右侧框输入对应命令，没有相应的响应，命令行界面报如下错误： <img alt="image" width="1433" src="https://private-user-images.githubusercontent.com/33169348/280962691-d295da05-e323-4a55-8696-6b355bca64c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzYxMDMsIm5iZiI6MTcwMTc3NTgwMywicGF0aCI6Ii8zMzE2OTM0OC8yODA5NjI2OTEtZDI5NWRhMDUtZTMyMy00YTU1LTg2OTYtNmIzNTViY2E2NGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDExMzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZTkwNmQyMGI1NzczZWY4NTA2MDgxYmFmMmIyZWQ3OWQ0YmRjNDU3YWEyYTRjNTg5YTMyYmJlYzRhODQ0ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RbMjc0JANk7uT8kgzvcFyFrnEj659b724NkPqUc4U_4">
> 
> 想问下这个可以怎么解决呢？ 还有个疑问，在使用过程中未能找到chatgpt4 的账户密码设置地方，是和这个有关吗？

想问下你怎么解决的呀 我也找不到哪里输入key
