### ISSUE TITLE
Not able to run the copilot

### ISSUE THREAD

**Issue by AutoAPEAI** [ddupont808/GPT-4V-Act#8]
I cloned your repo and tried to run it with `npm start` command, however I'm getting following error:

> ai-browser@1.0.0 start

> electron .

2023-12-02 16:36:21.723 Electron[6233:316840] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

Acquired webviewId 2

(node:6233) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'tmp/screenshot.png'

(Use `Electron --trace-warnings ...` to show where the warning was created)

(node:6233) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

How can I fix this problem?

**Comment by balajikummari** [comment]
@AutoAPEAI  create a directory 'tmp' at the root of the project

**Comment by AutoAPEAI** [comment]
Thx!!! Are you working on making it a product?
